### ISSUE TITLE
Texture transfer from scanner to scene

### ISSUE THREAD

**Issue by jukkae** [kids-aquarium/aquarium#22]
PNG encoding is a bottleneck, and not really required either. Current consensus is reimplementing with transferring the raw texture as a byte array from the scanner to the `FishManager`.

@sourya-sen let's talk about this on Discord, me and @delphi1004 talked about this face to face.

**Comment by jukkae** [comment]
Related to #8

**Comment by sourya-sen** [comment]
This can probably be closed now?

**Comment by jukkae** [comment]
Yes, thanks for the reminder!
