### ISSUE TITLE
Fish animation

### ISSUE THREAD

**Issue by jukkae** [kids-aquarium/aquarium#7]
How to do bendy floppy swim thingy?

**Comment by sourya-sen** [comment]
Vertex shader? Or actual mesh deformation? Or is there an easier way? We
could also get the base mesh from blender or something with in built
animation... I’ll try to look into it as soon as I have some time.

**Comment by jukkae** [comment]
Vertex shaders should be pretty easy to implement. However, it's not completely trivial to make that look nice and glitch-free, though if or not that matters is another question.

Unity supports both skeletal animation and blend shapes, and in this case we could probably use either. Whichever is easiest. I haven't used either in Unity, so can't really comment on that.

Yet another idea I just had would be to model the fish as a number of rectangles attached to each other with joints, probably hinge joints. Then, it'd be possible to manipulate the joints directly.

I'll think about this a bit too, let me know if you develop feelings about the topic.

**Comment by jukkae** [comment]
Implemented as keyframed animation.
